### PR TITLE
PodCast Entry and functionality

### PR DESCRIPTION
**Pull request by ElCapitanDre**
Hey, I'm probably not alone when saying this, but I'm a podcast fan, and thought that maybe you guys would like this functionality.

So I created an entry in the menu for podcasts.

Check it out, and see if its to your liking.

(First contribution to a repo that isn't mine, so if you see anything that isnt quite up to spec, let me know!)

image

image

image

### CODE REVIEW

**Comment by dupontgu** [comment]
Looks rad up front - will review closer when I get a little more time. Totally fine with this getting pulled in to master.

**Comment by ElCapitanDre** [comment]
> Looks rad up front - will review closer when I get a little more time. Totally fine with this getting pulled in to master.

Great. Have also been working on the settings menu, for wi-fi, bluetooth, etc. Been also lacking on time, so that one probably will take a little longer XD. Thanks for the feedback, and thanks for giving me a new play toy to brighten up these quarantine days!

**Comment by rsappia** [comment]
@ElCapitanDre thanks for sharing! I tested yout podcast code and runs great!

I was thinking, it would be great to have a menu item to shutdown the ipod. On the other hand, a menu item called "Sync" to call the method refresh_data() whenever the user wants :). 

The other functions you mentioned would be great to round up the design :))) 

I am working now on the power management side, will share circuits as soon as I am ready.

**Comment by ElCapitanDre** [comment]
Sorry for the delay in the response but I think I resolved all conflicts. No rush, merge when you want it ;)

**Comment by ruvido** [comment]
Hi, thanks for the update.

Is it merged now on master?

Thanks

**Comment by ElCapitanDre** [comment]
Hey @ruvido it isnt yet. I think only @dupontgu can do that as of now

**Comment by dupontgu** [comment]
Sorry for holding things up. Will merge now.

**Pull request merged**
